var FFI = require('node-ffi');
var CXString = exports.CXString = FFI.Struct([
    ['pointer', 'data'],
    ['uint32', 'private_flags'], ]);
var CXSourceLocation = exports.CXSourceLocation = FFI.Struct([
    ['pointer', 'ptr_data'],
    ['uint32', 'int_data'], ]);
var CXSourceRange = exports.CXSourceRange = FFI.Struct([
    ['pointer', 'ptr_data'],
    ['uint32', 'begin_int_data'],
    ['uint32', 'end_int_data'], ]);
var CXTUResourceUsage = exports.CXTUResourceUsage = FFI.Struct([
    ['pointer', 'data'],
    ['uint32', 'numEntries'],
    ['pointer', 'entries'], ]);
var CXCursor = exports.CXCursor = FFI.Struct([
    ['uint32', 'kind'],
    ['int32', 'xdata'],
    ['pointer', 'data'], ]);
var CXType = exports.CXType = FFI.Struct([
    ['uint32', 'kind'],
    ['pointer', 'data'], ]);
var CXToken = exports.CXToken = FFI.Struct([
    ['pointer', 'int_data'],
    ['pointer', 'ptr_data'], ]);
var CXCursorAndRangeVisitor = exports.CXCursorAndRangeVisitor = FFI.Struct([
    ['pointer', 'context'],
    ['pointer', 'visit'], ]);
var CXIdxLoc = exports.CXIdxLoc = FFI.Struct([
    ['pointer', 'ptr_data'],
    ['uint32', 'int_data'], ]);
exports.libclang = new FFI.Library('libclang', {
    clang_getCString: ['string', [CXString]],
    clang_disposeString: ['void', [CXString]],
    clang_createIndex: ['pointer', ['int32', 'int32']],
    clang_disposeIndex: ['void', ['pointer']],
    clang_getFileName: [CXString, ['pointer']],
    clang_getFileTime: ['long', ['pointer']],
    clang_isFileMultipleIncludeGuarded: ['uint32', ['pointer', 'pointer']],
    clang_getFile: ['pointer', ['pointer', 'string']],
    clang_getNullLocation: [CXSourceLocation, []],
    clang_equalLocations: ['uint32', [CXSourceLocation, CXSourceLocation]],
    clang_getLocation: [CXSourceLocation, ['pointer', 'pointer', 'uint32', 'uint32']],
    clang_getLocationForOffset: [CXSourceLocation, ['pointer', 'pointer', 'uint32']],
    clang_getNullRange: [CXSourceRange, []],
    clang_getRange: [CXSourceRange, [CXSourceLocation, CXSourceLocation]],
    clang_equalRanges: ['uint32', [CXSourceRange, CXSourceRange]],
    clang_Range_isNull: ['int32', [CXSourceRange]],
    clang_getExpansionLocation: ['void', [CXSourceLocation, 'pointer', 'pointer', 'pointer', 'pointer']],
    clang_getPresumedLocation: ['void', [CXSourceLocation, 'pointer', 'pointer', 'pointer']],
    clang_getInstantiationLocation: ['void', [CXSourceLocation, 'pointer', 'pointer', 'pointer', 'pointer']],
    clang_getSpellingLocation: ['void', [CXSourceLocation, 'pointer', 'pointer', 'pointer', 'pointer']],
    clang_getRangeStart: [CXSourceLocation, [CXSourceRange]],
    clang_getRangeEnd: [CXSourceLocation, [CXSourceRange]],
    clang_getNumDiagnosticsInSet: ['uint32', ['pointer']],
    clang_getDiagnosticInSet: ['pointer', ['pointer', 'uint32']],
    clang_loadDiagnostics: ['pointer', ['string', 'pointer', 'pointer']],
    clang_disposeDiagnosticSet: ['void', ['pointer']],
    clang_getChildDiagnostics: ['pointer', ['pointer']],
    clang_getNumDiagnostics: ['uint32', ['pointer']],
    clang_getDiagnostic: ['pointer', ['pointer', 'uint32']],
    clang_getDiagnosticSetFromTU: ['pointer', ['pointer']],
    clang_disposeDiagnostic: ['void', ['pointer']],
    clang_formatDiagnostic: [CXString, ['pointer', 'uint32']],
    clang_defaultDiagnosticDisplayOptions: ['uint32', []],
    clang_getDiagnosticSeverity: ['uint32', ['pointer']],
    clang_getDiagnosticLocation: [CXSourceLocation, ['pointer']],
    clang_getDiagnosticSpelling: [CXString, ['pointer']],
    clang_getDiagnosticOption: [CXString, ['pointer', 'pointer']],
    clang_getDiagnosticCategory: ['uint32', ['pointer']],
    clang_getDiagnosticCategoryName: [CXString, ['uint32']],
    clang_getDiagnosticNumRanges: ['uint32', ['pointer']],
    clang_getDiagnosticRange: [CXSourceRange, ['pointer', 'uint32']],
    clang_getDiagnosticNumFixIts: ['uint32', ['pointer']],
    clang_getDiagnosticFixIt: [CXString, ['pointer', 'uint32', 'pointer']],
    clang_getTranslationUnitSpelling: [CXString, ['pointer']],
    clang_createTranslationUnitFromSourceFile: ['pointer', ['pointer', 'string', 'int32', 'pointer', 'uint32', 'pointer']],
    clang_createTranslationUnit: ['pointer', ['pointer', 'string']],
    clang_defaultEditingTranslationUnitOptions: ['uint32', []],
    clang_parseTranslationUnit: ['pointer', ['pointer', 'string', 'pointer', 'int32', 'pointer', 'uint32', 'uint32']],
    clang_defaultSaveOptions: ['uint32', ['pointer']],
    clang_saveTranslationUnit: ['int32', ['pointer', 'string', 'uint32']],
    clang_disposeTranslationUnit: ['void', ['pointer']],
    clang_defaultReparseOptions: ['uint32', ['pointer']],
    clang_reparseTranslationUnit: ['int32', ['pointer', 'uint32', 'pointer', 'uint32']],
    clang_getTUResourceUsageName: ['string', ['uint32']],
    clang_getCXTUResourceUsage: [CXTUResourceUsage, ['pointer']],
    clang_disposeCXTUResourceUsage: ['void', [CXTUResourceUsage]],
    clang_getNullCursor: [CXCursor, []],
    clang_getTranslationUnitCursor: [CXCursor, ['pointer']],
    clang_equalCursors: ['uint32', [CXCursor, CXCursor]],
    clang_Cursor_isNull: ['int32', [CXCursor]],
    clang_hashCursor: ['uint32', [CXCursor]],
    clang_getCursorKind: ['uint32', [CXCursor]],
    clang_isDeclaration: ['uint32', ['uint32']],
    clang_isReference: ['uint32', ['uint32']],
    clang_isExpression: ['uint32', ['uint32']],
    clang_isStatement: ['uint32', ['uint32']],
    clang_isAttribute: ['uint32', ['uint32']],
    clang_isInvalid: ['uint32', ['uint32']],
    clang_isTranslationUnit: ['uint32', ['uint32']],
    clang_isPreprocessing: ['uint32', ['uint32']],
    clang_isUnexposed: ['uint32', ['uint32']],
    clang_getCursorLinkage: ['uint32', [CXCursor]],
    clang_getCursorAvailability: ['uint32', [CXCursor]],
    clang_getCursorLanguage: ['uint32', [CXCursor]],
    clang_Cursor_getTranslationUnit: ['pointer', [CXCursor]],
    clang_createCXCursorSet: ['pointer', []],
    clang_disposeCXCursorSet: ['void', ['pointer']],
    clang_CXCursorSet_contains: ['uint32', ['pointer', CXCursor]],
    clang_CXCursorSet_insert: ['uint32', ['pointer', CXCursor]],
    clang_getCursorSemanticParent: [CXCursor, [CXCursor]],
    clang_getCursorLexicalParent: [CXCursor, [CXCursor]],
    clang_getOverriddenCursors: ['void', [CXCursor, 'pointer', 'pointer']],
    clang_disposeOverriddenCursors: ['void', ['pointer']],
    clang_getIncludedFile: ['pointer', [CXCursor]],
    clang_getCursor: [CXCursor, ['pointer', CXSourceLocation]],
    clang_getCursorLocation: [CXSourceLocation, [CXCursor]],
    clang_getCursorExtent: [CXSourceRange, [CXCursor]],
    clang_getCursorType: [CXType, [CXCursor]],
    clang_getTypedefDeclUnderlyingType: [CXType, [CXCursor]],
    clang_getEnumDeclIntegerType: [CXType, [CXCursor]],
    clang_getEnumConstantDeclValue: ['longlong', [CXCursor]],
    clang_getEnumConstantDeclUnsignedValue: ['ulonglong', [CXCursor]],
    clang_equalTypes: ['uint32', [CXType, CXType]],
    clang_getCanonicalType: [CXType, [CXType]],
    clang_isConstQualifiedType: ['uint32', [CXType]],
    clang_isVolatileQualifiedType: ['uint32', [CXType]],
    clang_isRestrictQualifiedType: ['uint32', [CXType]],
    clang_getPointeeType: [CXType, [CXType]],
    clang_getTypeDeclaration: [CXCursor, [CXType]],
    clang_getDeclObjCTypeEncoding: [CXString, [CXCursor]],
    clang_getTypeKindSpelling: [CXString, ['uint32']],
    clang_getFunctionTypeCallingConv: ['uint32', [CXType]],
    clang_getResultType: [CXType, [CXType]],
    clang_getNumArgTypes: ['uint32', [CXType]],
    clang_getArgType: [CXType, [CXType, 'uint32']],
    clang_isFunctionTypeVariadic: ['uint32', [CXType]],
    clang_getCursorResultType: [CXType, [CXCursor]],
    clang_isPODType: ['uint32', [CXType]],
    clang_getElementType: [CXType, [CXType]],
    clang_getNumElements: ['longlong', [CXType]],
    clang_getArrayElementType: [CXType, [CXType]],
    clang_getArraySize: ['longlong', [CXType]],
    clang_isVirtualBase: ['uint32', [CXCursor]],
    clang_getCXXAccessSpecifier: ['uint32', [CXCursor]],
    clang_getNumOverloadedDecls: ['uint32', [CXCursor]],
    clang_getOverloadedDecl: [CXCursor, [CXCursor, 'uint32']],
    clang_getIBOutletCollectionType: [CXType, [CXCursor]],
    clang_visitChildren: ['uint32', [CXCursor, 'pointer', 'pointer']],
    clang_getCursorUSR: [CXString, [CXCursor]],
    clang_constructUSR_ObjCClass: [CXString, ['string']],
    clang_constructUSR_ObjCCategory: [CXString, ['string', 'string']],
    clang_constructUSR_ObjCProtocol: [CXString, ['string']],
    clang_constructUSR_ObjCIvar: [CXString, ['string', CXString]],
    clang_constructUSR_ObjCMethod: [CXString, ['string', 'uint32', CXString]],
    clang_constructUSR_ObjCProperty: [CXString, ['string', CXString]],
    clang_getCursorSpelling: [CXString, [CXCursor]],
    clang_getCursorDisplayName: [CXString, [CXCursor]],
    clang_getCursorReferenced: [CXCursor, [CXCursor]],
    clang_getCursorDefinition: [CXCursor, [CXCursor]],
    clang_isCursorDefinition: ['uint32', [CXCursor]],
    clang_getCanonicalCursor: [CXCursor, [CXCursor]],
    clang_CXXMethod_isStatic: ['uint32', [CXCursor]],
    clang_CXXMethod_isVirtual: ['uint32', [CXCursor]],
    clang_getTemplateCursorKind: ['uint32', [CXCursor]],
    clang_getSpecializedCursorTemplate: [CXCursor, [CXCursor]],
    clang_getCursorReferenceNameRange: [CXSourceRange, [CXCursor, 'uint32', 'uint32']],
    clang_getTokenKind: ['uint32', [CXToken]],
    clang_getTokenSpelling: [CXString, ['pointer', CXToken]],
    clang_getTokenLocation: [CXSourceLocation, ['pointer', CXToken]],
    clang_getTokenExtent: [CXSourceRange, ['pointer', CXToken]],
    clang_tokenize: ['void', ['pointer', CXSourceRange, 'pointer', 'pointer']],
    clang_annotateTokens: ['void', ['pointer', 'pointer', 'uint32', 'pointer']],
    clang_disposeTokens: ['void', ['pointer', 'pointer', 'uint32']],
    clang_getCursorKindSpelling: [CXString, ['uint32']],
    clang_getDefinitionSpellingAndExtent: ['void', [CXCursor, 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer']],
    clang_enableStackTraces: ['void', []],
    clang_executeOnThread: ['void', ['pointer', 'pointer', 'uint32']],
    clang_getCompletionChunkKind: ['uint32', ['pointer', 'uint32']],
    clang_getCompletionChunkText: [CXString, ['pointer', 'uint32']],
    clang_getCompletionChunkCompletionString: ['pointer', ['pointer', 'uint32']],
    clang_getNumCompletionChunks: ['uint32', ['pointer']],
    clang_getCompletionPriority: ['uint32', ['pointer']],
    clang_getCompletionAvailability: ['uint32', ['pointer']],
    clang_getCompletionNumAnnotations: ['uint32', ['pointer']],
    clang_getCompletionAnnotation: [CXString, ['pointer', 'uint32']],
    clang_getCursorCompletionString: ['pointer', [CXCursor]],
    clang_defaultCodeCompleteOptions: ['uint32', []],
    clang_codeCompleteAt: ['pointer', ['pointer', 'string', 'uint32', 'uint32', 'pointer', 'uint32', 'uint32']],
    clang_sortCodeCompletionResults: ['void', ['pointer', 'uint32']],
    clang_disposeCodeCompleteResults: ['void', ['pointer']],
    clang_codeCompleteGetNumDiagnostics: ['uint32', ['pointer']],
    clang_codeCompleteGetDiagnostic: ['pointer', ['pointer', 'uint32']],
    clang_codeCompleteGetContexts: ['ulonglong', ['pointer']],
    clang_codeCompleteGetContainerKind: ['uint32', ['pointer', 'pointer']],
    clang_codeCompleteGetContainerUSR: [CXString, ['pointer']],
    clang_codeCompleteGetObjCSelector: [CXString, ['pointer']],
    clang_getClangVersion: [CXString, []],
    clang_toggleCrashRecovery: ['void', ['uint32']],
    clang_getInclusions: ['void', ['pointer', 'pointer', 'pointer']],
    clang_getRemappings: ['pointer', ['string']],
    clang_remap_getNumFiles: ['uint32', ['pointer']],
    clang_remap_getFilenames: ['void', ['pointer', 'uint32', 'pointer', 'pointer']],
    clang_remap_dispose: ['void', ['pointer']],
    clang_findReferencesInFile: ['void', [CXCursor, 'pointer', CXCursorAndRangeVisitor]],
    clang_index_isEntityObjCContainerKind: ['int32', ['uint32']],
    clang_index_getObjCContainerDeclInfo: ['pointer', ['pointer']],
    clang_index_getObjCInterfaceDeclInfo: ['pointer', ['pointer']],
    clang_index_getObjCCategoryDeclInfo: ['pointer', ['pointer']],
    clang_index_getObjCProtocolRefListInfo: ['pointer', ['pointer']],
    clang_index_getIBOutletCollectionAttrInfo: ['pointer', ['pointer']],
    clang_index_getCXXClassDeclInfo: ['pointer', ['pointer']],
    clang_index_getClientContainer: ['pointer', ['pointer']],
    clang_index_setClientContainer: ['void', ['pointer', 'pointer']],
    clang_index_getClientEntity: ['pointer', ['pointer']],
    clang_index_setClientEntity: ['void', ['pointer', 'pointer']],
    clang_IndexAction_create: ['pointer', ['pointer']],
    clang_IndexAction_dispose: ['void', ['pointer']],
    clang_indexSourceFile: ['int32', ['pointer', 'pointer', 'pointer', 'uint32', 'uint32', 'string', 'pointer', 'int32', 'pointer', 'uint32', 'pointer', 'uint32']],
    clang_indexTranslationUnit: ['int32', ['pointer', 'pointer', 'pointer', 'uint32', 'uint32', 'pointer']],
    clang_indexLoc_getFileLocation: ['void', [CXIdxLoc, 'pointer', 'pointer', 'pointer', 'pointer', 'pointer']],
    clang_indexLoc_getCXSourceLocation: [CXSourceLocation, [CXIdxLoc]],
});